language: node_js
warnings_are_errors: false
node_js:
- '9'
before_script:
- export CI=false
cache:
  yarn: true
  directories:
  - node_modules
before_deploy:
- yarn build
deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: kxcw+seuq6gqoCOZb5tEbmqHEPA2j8mwk/P+obzEAXf4wloc5NlKueNEP/kF2P260l+fd3tBMITLD1VU7sffbn8zUNeW2PcT2F1p4WYjfTiRvAPKRFhNBHOlWxA8N0p9TFgAsl4DS1sE6HJXj5yhPeegMLuJD+BVMyEEvmE7018m0rEfgSDuZZxxrj/GiUgyPD6k/HkiL/uwRRJLwRj9YfMl8H0xmARxN3FF4S73dL8lqGX6sOPyo2YQ31pNDUQfI2kC1gpvApOO3FnALjAcixJkwj4fohhibXAmlo21ydB0H4tN8IYfn0HpixykB5hPUMz1VdSJR/yUR98buFvOuNicZMq6hqKQTmezgHRVA/zIzMfhwniL3S+KZVG9dx7LTXGZkWWKr/yDuw2YjhPCvjiiQVUXCaKhhzJHMMoakXgq1a/EU3EC7jpV/yUelO08QF711rE/o3f8cTimx/ompIv5fOfDVusscKHF/DDhpSma9our4iU0AKrKGYodV52oOp0DNQ2MiM/gZIfB+Yq5QY4bLT2UbGU5RQKbSweDMr9CgDXEpRGB7OCR8qXbEZVx8w/Se7mL8he41xp2Xzh5MCINEjk3Fg6gmSbmlTTF6fizlUm9HALMGuM9vOq4r7avVFPDf8HdnIyr7cyc96ffVBiTa+HF0vUpkplbqKlpzVc=
env:
  global:
  - secure: kxcw+seuq6gqoCOZb5tEbmqHEPA2j8mwk/P+obzEAXf4wloc5NlKueNEP/kF2P260l+fd3tBMITLD1VU7sffbn8zUNeW2PcT2F1p4WYjfTiRvAPKRFhNBHOlWxA8N0p9TFgAsl4DS1sE6HJXj5yhPeegMLuJD+BVMyEEvmE7018m0rEfgSDuZZxxrj/GiUgyPD6k/HkiL/uwRRJLwRj9YfMl8H0xmARxN3FF4S73dL8lqGX6sOPyo2YQ31pNDUQfI2kC1gpvApOO3FnALjAcixJkwj4fohhibXAmlo21ydB0H4tN8IYfn0HpixykB5hPUMz1VdSJR/yUR98buFvOuNicZMq6hqKQTmezgHRVA/zIzMfhwniL3S+KZVG9dx7LTXGZkWWKr/yDuw2YjhPCvjiiQVUXCaKhhzJHMMoakXgq1a/EU3EC7jpV/yUelO08QF711rE/o3f8cTimx/ompIv5fOfDVusscKHF/DDhpSma9our4iU0AKrKGYodV52oOp0DNQ2MiM/gZIfB+Yq5QY4bLT2UbGU5RQKbSweDMr9CgDXEpRGB7OCR8qXbEZVx8w/Se7mL8he41xp2Xzh5MCINEjk3Fg6gmSbmlTTF6fizlUm9HALMGuM9vOq4r7avVFPDf8HdnIyr7cyc96ffVBiTa+HF0vUpkplbqKlpzVc=
